<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Avalonia.Controls</RootNamespace>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>
  
  <PropertyGroup>
    <PackageId>Avalonia.Controls.TreeDataGrid</PackageId>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="$(AvaloniaVersion)" />    
  </ItemGroup>
</Project>
